### ISSUE TITLE
Tried to load unavailable font: 'thisIsNotAFont'

### ISSUE THREAD

**Issue by mbxtr** [steveruizok/fontloader#2]
When using fontloader and sharing my Framer project on a web link, sometimes the prototype wouldn't load in Chrome and I'd see this error in the console. I never ran into it in Safari or Mobile Safari.

<img width="729" alt="screen shot 2018-04-06 at 3 00 30 pm" src="https://user-images.githubusercontent.com/238096/38441782-88f574f2-39ab-11e8-875b-223d56d98008.png">

On line 191 I changed the fontFamily from "thisIsNotAFont" to "Arial" and it seemed to fix that error. Is there a reason a fake font name is used?

**Comment by steveruizok** [comment]
Fixed! This one should never have gotten out into the wild.
